### PR TITLE
WIP: Implement automatic fixing of found issues

### PR DESCRIPTION
**Pull request by martin-helmich**

### CODE REVIEW

**Comment by tmotyl** [comment]
Hi
What is missing to have that merged?
Can I help somehow?

**Comment by martin-helmich** [comment]
TBH, I kind of lost track of this one. I still remember this PR involving quite a bit of refactoring, before my attention shifted elsewhere...

My intention was to implement a few of the auto-fixes by manipulating the AST and then re-generating the code from the AST. However, the drawback of that solution was that many finer formatting details (and also comments, iirc) were lost. I still remember thinking about refactoring the parser to generate an AST with nodes that have additional positional metadata to allow for selective re-generation of specific parts of the program, when my attention shifted away from this issue.

With the christmas break coming up (and not much else to do during lockdown 😷) I might actually find some time to pick this up again and maybe give it another push. 🙂

**Comment by martin-helmich** [comment]
It's been four years since I've last worked on this, so I'm officially abandoning this PR for the time being -- looking at the list of merge conflicts, it would probably be easier to start over, anyway. 😕

**Comment by tmotyl** [comment]
Hi Martin, 
can you clarify, whether this project or fractor (or both depending on sth) should be a home for "fixing" rules?
I see that fractor has some first rules for TS already. https://github.com/andreaswolf/fractor/blob/main/packages/typo3-fractor/docs/typo3-fractor-rules.md

**Comment by martin-helmich** [comment]
I still would like to see automatic fixing as a part of this tool (ref. #103).

The thing with this PR is that 1) this was never actually functional, 2) I haven't been able to spend appropriate time on it in years, and 3) that by now it has fallen so far behind the current master that it would probably be easiest to just start over.

**Pull request closed without merging**
